### ISSUE TITLE
Adding actions to clusters with none

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#10]
Hi Timo,

When building the Implementation Plan, after the clusters have been determined adding the actions comes next. Is it possible so that actions can be added when a user is on the 'categories' tab and has selected the 'thematic clusters' from the side menu? They could scroll down, see which clusters have no actions, click on that cluster and add actions from there? Would that be possible?

Thanks!

**Comment by tmfrnz** [comment]
Yes, it would be quite easy and straight forward to allow adding actions (and recommendations) to clusters (or any other suitable categories) from the category edit view, eg https://sadata-staging.firebaseapp.com/category/edit/159

I have opened an issue for this on the main repository
https://github.com/impactoss/impactoss-client/issues/326

**Comment by tmfrnz** [comment]
@ashbowe: this has been implemented in main repository and will be rolled out with the next release
