### ISSUE TITLE
Indicator Bug: error handling and messages not working as required/expected

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#11]
Hi Timo,

I just went to add an indicator and came across a small issue (that may actually be two small issues, I'm not sure). I entered information for an indicator and clicked save but nothing happened. I didn't see the error message as it was at the top of the screen and out of sight so could that be brought down to where the save button is? 

Additionally it didn't tell me what was wrong and so I didn't know what to fix. I thought it might be because I had put a due date in the past so tried to change that but it still came back with the error message. However, when I copied and pasted the information into a totally new indicator (by going back to the indicator home page) and only changing the date it saved OK. 

The issues therefore seemed to be:

- The error message bar was not visible on the page view when you have scrolled down and it does not give information about what the error is;
- If an error has been made and then rectified it still does not appear to save. 

Thanks

![something wrong](https://user-images.githubusercontent.com/21161841/30037902-e7bff030-921b-11e7-9a8a-df7d305cb8ce.png)

**Comment by tmfrnz** [comment]
Opened issue for error message out of view: https://github.com/impactoss/impactoss-client/issues/332

**Comment by tmfrnz** [comment]
Trying to reproduce:
### Past due date (new indicator and edit indicator)
Past due dates are allowed and do not result in error (however actual due dates are never generated in the past)

### End date before start date (new indicator) 
- Dates are checked on submit only, displaying a general error message above the form and individual error messages with the date fields "Start date must be before end date" and "End date must be after start date". 
- It would be better to validate already when leaving any date field (see https://github.com/impactoss/impactoss-client/issues/333). It may actually be sufficient however to only validate the end date (or better even the one most recently edited)
- After this error occurs the user will have to edit/touch both date fields to re-validate and allow re-submitting
- Once all field errors are corrected re-submitting successfully creates the indicator 

### End date before start date (edit indicator) 
- Dates are checked on submit only, but only the general error message above the form is displayed (should also show field specific errors https://github.com/impactoss/impactoss-client/issues/334)
- Updating the date fields re-submitting successfully updates the indicator

**Comment by tmfrnz** [comment]
@ashbowe: I could not exactly reproduce the issue you described. Maybe you can try again, documenting each interaction so I can reproduce?

Ultimately the desired behaviour should be:
- field validation occurs before submitting (https://github.com/impactoss/impactoss-client/issues/332)
- a general error message is displayed above the form while making sure it is visible (scroll to view https://github.com/impactoss/impactoss-client/issues/333)
- field specific error messages are displayed with each affected field

**Comment by tmfrnz** [comment]
Error handling and validation improved in next release.

Leaving open to verify it is working as expected.

**Comment by tmfrnz** [comment]
@ashbowe: could you verify this is working in the new version as expected? thanks

**Comment by ashbowe** [comment]
Hi Timo, yes that seems to be working, thanks

**Comment by tmfrnz** [comment]
Thanks!
