### ISSUE TITLE
Manager for SDGs

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#13]
Is it currently possible to allocate a manager for the SDGs? I couldn't see how to do this. Thanks.

**Comment by tmfrnz** [comment]
This is not currently possible but can be selectively turned on for each taxonomy. Currently this has only been configured for "Human Rights Bodies" https://github.com/impactoss/impactoss-server/blob/master/db/seeds.rb#L37

Once confirmed, we can easily turn this on also for SDGs (and any other taxonomy required)

**Comment by ashbowe** [comment]
Yes that would be great if possible please

**Comment by tmfrnz** [comment]
See https://github.com/nmrf/sadata-server/issues/4
