### ISSUE TITLE
websites spill over frame

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#15]
Very small issue! When you enter a website into one of the areas where that is allowed and the website url is reasonably long, the text does not get wrapped and spills out of the box. Is there a way to format this so that it stays within the container? Pic attached for reference

![image](https://user-images.githubusercontent.com/21161841/30040694-3009e968-923f-11e7-96dd-5a6f71546e3d.png)

**Comment by tmfrnz** [comment]
Thank you - I have opened an issue on the main repository
https://github.com/impactoss/impactoss-client/issues/331

**Comment by tmfrnz** [comment]
fixed in next release
