### ISSUE TITLE
Accessibility of public report attachments

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#16]
Just another small bug - when you set a report to 'public' it is still not accessible by the public (i.e. once you have signed out). I have added a report to the indicator - Draft Ombudsman Act passed in parliament (https://sadata-staging.firebaseapp.com/indicators/233) but cannot access it when I'm signed out.

**Comment by tmfrnz** [comment]
Thanks @ashbowe. These bug reports are invaluable.

**Comment by ashbowe** [comment]
Sorry it's all coming in a bit of a glut! making progress with the manual though. Hope to have finished the non-user section and to have moved onto the user section by the end of today (although leaving common case uses to the end)

**Comment by tmfrnz** [comment]
see https://github.com/impactoss/impactoss-client/issues/336

**Comment by tmfrnz** [comment]
fixed in next release
