### ISSUE TITLE
Status (filter list)

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#17]
Just another small issue - when you are not logged in and on either the action, indicator, recommendation or SDG tab, 'Status' still comes up as one of the filter options in the list on the left hand side. This is redundant as only public entities will be displayed. Can it be removed?

**Comment by tmfrnz** [comment]
Yes!

**Comment by tmfrnz** [comment]
See, https://github.com/impactoss/impactoss-client/issues/337

**Comment by tmfrnz** [comment]
fixed in next release
