### ISSUE TITLE
Cycle not showing when logged out

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#18]
Odd little bug - when you are logged out it shows all of the recommendations as having no cycle (see attached) but when you login they have all been allocated a cycle
![rec issue](https://user-images.githubusercontent.com/21161841/30144382-589214ec-93e7-11e7-9eca-779b26e5af3f.png)

**Comment by tmfrnz** [comment]
Very odd indeed! Will investigate...

**Comment by tmfrnz** [comment]
Apparently cycles are not available when not logged in
https://sadata-staging.firebaseapp.com/categories/2

**Comment by tmfrnz** [comment]
It appears that `draft` is set to `true` in the database for the 2 cycles available. Will set to `false`.

**Comment by tmfrnz** [comment]
Updated database. Leaving this issue open to further investigate the root cause of the draft field (categories should never be set to draft)

**Comment by tmfrnz** [comment]
Please refer to https://github.com/impactoss/impactoss-server/issues/276
