### ISSUE TITLE
Link for uploading public reports

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#19]
Hi Timo,

Just at the point in the manual about visitors entering reports - we are still having that feature right? And if so they will need to register as a user in order to be able to do so?

Thanks

**Comment by tmfrnz** [comment]
Yes, it is on the list and will also require the user to register.
https://github.com/impactoss/impactoss-client/issues/93

**Comment by tmfrnz** [comment]
@ashbowe we suggest to allow creating progress reports only from the single indicator view and not as originally discussed from the list/implementation plan view, at least for version 1, as this will 
- facilitate the login/register workflow
- make sure users actually open the indicator view and have the chance to learn what it is about (other than having to infer from the indicator title)

**Comment by ashbowe** [comment]
Hi Timo,

Ok, no problem

**Comment by ashbowe** [comment]
Hi Timo - I'm just writing this bit for the manual and it looks as though there is no link to upload a report unless you are already registered as a user and signed in. If that's correct that means that someone visiting the site would need to know that they can submit information - shouldn't there be an upload link that then takes them to the register process if they aren't already registered?

**Comment by tmfrnz** [comment]
Hmm, for me it works as follows (note on [staging only](https://sadata-staging.firebaseapp.com/indicators) not on production - maybe you are still being served an outdated/cached version of the app? please try reloading the site while holding the `Ctrl` key):

- Sign out
- Select an indicator from indicator list
- Use one of the add report buttons to add a report (visible also when signed out)

![screenshot 2017-10-06 15 56 06](https://user-images.githubusercontent.com/5811956/31281305-5005c7d6-aaaf-11e7-9473-9100f31a7045.png)

- Sign in or register (also note the messages)

![screenshot 2017-10-06 15 59 36](https://user-images.githubusercontent.com/5811956/31281352-71db6050-aaaf-11e7-9c40-12850877cb36.png)
![image](https://user-images.githubusercontent.com/5811956/31281349-6f564d22-aaaf-11e7-8566-8bc4d88bb14b.png)

- Add report (also note the changed sign-in state in the top navigation)

![image](https://user-images.githubusercontent.com/5811956/31281373-8917365e-aaaf-11e7-9bf3-59896407703a.png)

**Comment by ashbowe** [comment]
Hi Timo,

It must have been the outdated version as it worked fine after I had
reloaded as suggested.

Many thanks. Ash

**Comment by tmfrnz** [comment]
Excellent! We will look into ways to force the browser to re-cache any outdated files
see https://github.com/impactoss/impactoss-client/issues/364
