### ISSUE TITLE
Remove "Desired outcome" and "Measures" fields from action views

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#20]
Hi Timo,

I've just started work on the manual again and was doing the Actions page. When adding a new action there is a box for desired outcome and outcome summary. This seemed to be to be a bit of a duplication with the indicator that could be attributed to it and I am wondering whether these two boxes could be removed. I can see there is a distinction but I am not sure whether it will be clear enough to the end user - what do you think?

**Comment by tmfrnz** [comment]
These fields have been introduced to map the current structure of the NZ NPA where (lacking any associated indicators) they were originally called "Desired outcome" and "Measures": eg http://npa.hrc.co.nz/#/action/30

When adopting the new structure (that is having indicator entities) we have preliminarily renamed "Measures" to "Indicator summary" to allow for providing high level summaries of the associated indicators that are visible without having to open them - also this can be used when not having any indicators defined.

Regardless, in the end there are 2 extra fields for actions to play with and we can either rename them for clarity or remove them for the Samoan implementation (and maybe also for the central default version).

**Comment by ashbowe** [comment]
I think removing them if that's OK - thanks Timo

**Comment by tmfrnz** [comment]
removed for Samoa implementation
https://github.com/nmrf/sadata/commit/7b88bafb6bc1f1a9f3955c4e73d13b214db5731c
