### ISSUE TITLE
'Add' feature not working

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#22]
Hi Timo, when I am logged in and go to add a new recommendation or action I then go to make a connection (either with an action or indicator and whilst I can select ones that are already there, the 'add' button doesn't appear to be working. This seems to be the case when adding new entities and then trying to add a new connection. However, this add function appears to work ok when working with the categories on the right hand side of the page

**Comment by tmfrnz** [comment]
Thanks @ashbowe. Will fix this in next release, see issue created in main repository: https://github.com/impactoss/impactoss-client/issues/353

**Comment by tmfrnz** [comment]
Fixed in impactoss - will be rolled out with next release
