### ISSUE TITLE
Multiple documents for progress reports

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#23]
Timo,

Would it be a lot of effort (or advisable) to allow users to upload more than one document for a particular progress report? I guess the alternative is that an extraordinary report could be uploaded instead but sometimes it might be useful if two docs could be uploaded to the one report, I imagine.

**Comment by tmfrnz** [comment]
@ashbowe adding multiple documents to one report should not be a lot of effort but also not negligible and would include considering technical and user interface options, and finally the actual implementation (possibly only client-side but would have to check). If it would be advisable I am not sure but for certain use cases I could see the benefit. While not as user friendly, an effective workaround with the current set-up would of course be simply zipping multiple documents and add the zip file.

**Comment by ashbowe** [comment]
Thanks Timo, sounds good

**Comment by tmfrnz** [comment]
Created an issue in the core repository to consider this enhancement in the future
https://github.com/impactoss/impactoss-client/issues/354
