### ISSUE TITLE
Indicators searchable by user? 

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#24]
Another question of how much work it would take where I strongly suspect the answer is a lot but I hope otherwise! 

Would it be possible to filter indicators by user. This would have two advantages. First it would allow you to quickly see who is responsible for how much but more importantly it would allow easy identification of indicators which do not have a user assigned (and would therefore get no data)

**Comment by tmfrnz** [comment]
Fully agree and not too much work: see https://github.com/impactoss/impactoss-client/issues/362
