### ISSUE TITLE
Adding Users to Indicators

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#25]
Hi Timo,

I just registered as a new user with my UN email address and the name 'Ashley Bowe'. However, when I logged in with my gmail admin account and went to assign an indicator to the new 'Ashley Bowe' account I was not on the list to do so, and neither was Edith a one or two other user accounts that appear i the users panel. Could you have a look into why this is please? Thanks

**Comment by ashbowe** [comment]
Hi Timo - ignore this. I think it is because I then have to change their status to contributor. I'll send over an email about this issue in more general terms

**Comment by tmfrnz** [comment]
Yes - a user has to be at least a "contributor" to be assignable to indicators
