### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#28]
Hi Timo - when a member of the public wants to upload some info they register and they can then submit a report for any indicator. However, their user role is still unassigned at this point, meaning they cannot be assigned to an indicator. That is correct but I think it might be helpful to have a name for those people, especially for the manual. 

I have made the distinction by calling the NGO group (for the sake of a title) who just register and upload to any indicator as 'contributors' and users who are to be assigned to specific indicators as 'indicator owners' 

Does this make sense and if so can we easily change the name in the database from 'contributor; to 'indicator owner'? This would make the 'role unassigned' the contributors.

**Comment by tmfrnz** [comment]
I think we need to be careful distinguishing user roles (that technically define each user's rights) and user functions (that more so define the user's duties) where roles are prerequisites for user functions (for some functions also an assignment is needed). How about the following classification?


### Technical user roles 
- Not registered (actually a non-role): 
  - can view public content
  - can register and become Guest
- Guest: 
  - only requires registration
  - can create draft progress reports (can become a guest contributor)
  - all the above
- Contributor: 
  - can be assigned to indicator (thus become indicator manager/owner) 
  - create public progress reports for indicators assigned to
  - can view draft content
  - all the above
- Manager: 
  - can be assigned to category (thus become a category manager)
  - can assign Contributor to indicator
  - can promote Guest to Contributor 
  - can create and update categories and other entities
  - all the above
- Administrator:
  - can assign Manager to category
  - can promote users to Manager and Administrator
  - can create and update pages
  - all the above

### User functions (types of user)
- Visitor
  - no role required (Role: Not registered)
- Guest contributor 
  - requires registration (automatically assigned Guest role)
- Indicator Manager _(do not think they are owners as they cannot assign contributors for example)_
  - requires at least role Contributor
  - requires assignment to indicator
  - responsible for creating reports for indicators
  - receives due and overdue reminder emails
- Category Manager 
  - requires at least role Manager
  - requires assignment to category
  - responsible for assigning Contributors to indicators
  - responsible for overseeing report creation for indicators
  - receives overdue reminder emails
- Application Administrator
  - requires role Administrator
  - responsible for assigning Managers to categories

Of course the public role and function names can be changed (not private database names though) but it is important not to confuse them and keep them somewhat distinct. This should also be reflected in the manual - I will have a go later

**Comment by tmfrnz** [comment]
Also could consider adding user types
- Implementation Plan Manager
  - Responsible for developing and updating the National Implementation Plan
- Content Manager
  - Responsible for editorial content.

**Comment by tmfrnz** [comment]
Ended up "nesting" those functions with roles in the manual. Again role names can easily be changed
https://github.com/impactoss/impactoss-server/blob/master/db/seeds.rb#L25
