### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#3]
Sorry another little thing - I was just using the search function to search for a recommendation and searched for 'CRC91' as I knew there was a rec with that reference. However, it did not come up in the search results. I tried for other 'CRC' referenced recs but they didn't come up. Searching for the UPR number reference is successful though.

**Comment by ashbowe** [comment]
Update: It seems to work for the letters. I.e if you just type in 'CRC' it brings up all recs with 'CRC' in the reference (but not in the body) but as soon as you add a number as well then the search doesn't work

**Comment by tmfrnz** [comment]
Very weird! Thanks for reporting - one more for the list.

**Comment by tmfrnz** [comment]
See https://github.com/dumparkltd/hr-nmrf-client/issues/247

**Comment by tmfrnz** [comment]
Fixed on staging 
https://sadata-staging.firebaseapp.com/recommendations?search=crc91
