### ISSUE TITLE
'Categories' page not loading

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#31]
Hi Timo,

Sorry to bother you. I'm just starting to prepare for the workshop on Thursday and for some reason can't access the categories page. All of the other pages look to be loading fine and when I click on categories the URL shows the correct page but it just doesn't load. 

Could you have a quick look into it if you have a moment please? 

Thanks so much

**Comment by tmfrnz** [comment]
Works for me. A refresh resolved the issue, but we should check the error log next time this happens to gain insight into the nature of the problem
