### ISSUE TITLE
Batch import

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#33]
Two small issues:

1. When using the batch import template CSV file it also imports row 2 of the sheet (Title | Text, Reference | Text) as a recommendation. It's  no problem for the workshop tomorrow but would be handy to take out of the template csv file if possible

2. There is not a field in the template CSV file to mark whether it is in draft or public. I tried using the formats of both csv files you sent today but neither seemed to work. Is this possible or does the user have to change it after?

**Comment by ashbowe** [comment]
Another smallish issue is if you press the upload button twice, it uploads it twice. Is there any way of guarding against this? Other than these things, it all works great! Testing two browsers at the same time worked fine too

**Comment by tmfrnz** [comment]
@ashbowe thanks for raising these issues

Re: 2nd row
The 2nd row should simply be deleted before import or better replaced with
the content of the first item. Maybe we should improve the wording in the
app and/or the template file, eg 'Enter title here (text, required)'

Re: draft
The import feature is set up to force draft status for all items as a
safeguard, assuming items will be reviewed after import and/or connected to
other entities or categories before being published. This can however be
changed if you think it must

Re: double click
The button should in fact become inactive after the first click - I will
address this shortly.


On Wednesday, November 22, 2017, ashbowe <notifications@github.com> wrote:

> Another smallish issue is if you press the upload button twice, it uploads
> it twice. Is there any way of guarding against this? Other than these
> things, it all works great! Testing two browsers at the same time worked
> fine too
>


-- 
[image: dumpark] <http://dumpark.com/>

Timo Franz | *unfolddata.com <http://dumpark.com>*
timo@dumpark.com T +64 04 381 3725 M +64 022 011 8070 SKYPE tmfrnz
*Unfold Data Limited*

**Comment by tmfrnz** [comment]
Opened issues
- Re: 2nd row - https://github.com/impactoss/impactoss-client/issues/412
- Re: double click - https://github.com/impactoss/impactoss-client/issues/411

**Comment by tmfrnz** [comment]
@ashbowe

Re: 2nd row - added a note to the end of row 2 "Note: This row provides additional information about the columns only. Please replace or remove it before importing." (as all text this will be editable in the translations file)

Re: double click - I was not able to click the import button twice
