### ISSUE TITLE
Batch editing issue with mixed group

### ISSUE THREAD

**Issue by ashbowe** [nmrf/sadata#34]
Hi Timo,

I have just noticed a slight problem on the live site I think.

When you go to batch edit a group of recommendations you have selected, if there is a mixture of recs that already have that tag and those that don't the update doesn't work. E.g. if I select ten recs and five already have the CRC tage and 5 don't, when I cycle through the tickbox in the filter system to denote for them all to have it and press update, nothing happens. 

Not an urgent matter at all

**Comment by tmfrnz** [comment]
thanks @ashbowe. coincidentally I noticed that same bug yesterday, too
https://github.com/impactoss/impactoss-client/issues/420

I have since addressed this and will deploy the fix with the next Sadata update (on the demo site it should already working)
